POST http://localhost:3001/api/reviews/98567/save
Content-Type: application/json

{
	"email": "rodolfogal@hotmail.com",
	"rating": 5,
	"comment": "Not for the faint of heart",
	"id": "5e68cef04f49cc1750eb9b12"
}